---
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          package-name: '@awesomeorganization/servers'
          release-type: node
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_USERCONFIG: github.npmrc
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 16
          registry-url: https://npm.pkg.github.com
      - run: npm publish
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_USERCONFIG: npm.npmrc
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: npm publish
name: publish
'on':
  push:
    branches:
      - main
      - master
permissions: write-all
