---
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          package-name: '@awesomeorganization/servers'
          release-type: node
name: release-please
'on':
  push:
    branches:
      - main
      - master
